### ISSUE TITLE
V2: Visibility Hooks

### ISSUE THREAD

**Issue by FergusInLondon** [FergusInLondon/Runner#8]
When a `Strategy` is running, the execution is largely a "*black box*": there's little visibility as to what's actually happening - other than perhaps pre-defined log statements contained in the `algorunner` package - out of control of the `Strategy` object itself.

These hooks may be used for custom logging, troubleshooting, or triggering observability metrics.

## Requirements:

```
Feature: Hooks
  Hooks allow user-defined handlers to internal events in the AlgoRunner.

  Scenario: An invalid handler should be rejected
    Given a handler that isn't callable
     When that handler is registered
     Then an InvalidHookHandler exception is raised

  Scenario: Handler signatures are verified to match the hook
    Given an invalid handler with a different signature
     When that handler is registered
     Then an InvalidHookHandler exception is raised

  Scenario: Hook type should be validated when registering handler
    Given a valid handler for an unknown hook
     When that handler is registered
     Then an InvalidHookHandler exception is raised

  Scenario: A valid hook should be registered and triggered
    Given a valid handler for process_duration
     When that handler is registered
      and the process_duration hook is triggered
     Then no exception should be raised
      and the handler should be called

  Scenario: Multiple hooks should all be called
    Given 5 valid handlers for process_duration 
     When those handlers are registered
      and the process_duration hook is triggered
     Then no exception should be raised
      and the handlers should all be called
```

### Tasks

- [x] The definition of hooks - i.e. an `enum.Enum` containing different events that may occur during execution.
- [x] The definition of `Callable[<params>]` types for the callbacks expected for a given hook.
- [x] The ability to register hooks - i.e. `self.hook(hook_identifier, hook_callback)`, with the compatibility of the `type(hook_callback)` checked. (A failure to do could cause exceptions during execution: much better to fail before the strategy is running!)
- [x] Calling of hooks during specific events that may occur in the `Strategy` object.
